Repository tuist/XcodeGraph, pull requests merged in 2025-03, with the labels that each got.

#146 fix: mapping fails when bundle product name differs from target name
  Package.resolved
  Sources/XcodeGraphMapper/Mappers/Graph/XcodeGraphMapper.swift
  Tests/XcodeGraphMapperTests/MapperTests/Graph/XcodeGraphMapperTests.swift
  Tests/XcodeGraphMapperTests/TestData/PBXNativeTarget+TestData.swift
Labels: bug, size:M, lgtm

#145 fix: fix project paths respecting nested projects
  Sources/XcodeGraphMapper/Mappers/Graph/XcodeGraphMapper.swift
  Tests/XcodeGraphMapperTests/MapperTests/Graph/XcodeGraphMapperTests.swift
Labels: bug, size:M, lgtm

#147 refactor: migrate to xcodeproj 9
  Package.resolved
  Package.swift
  Sources/XcodeGraph/Models/Settings.swift
  Sources/XcodeGraphMapper/Extensions/PBXProject+Extensions.swift
  Sources/XcodeGraphMapper/Mappers/Phases/PBXCopyFilesBuildPhaseMapper.swift
  Sources/XcodeGraphMapper/Mappers/Phases/PBXFrameworksBuildPhaseMapper.swift
  Sources/XcodeGraphMapper/Mappers/Phases/PBXHeadersBuildPhaseMapper.swift
  Sources/XcodeGraphMapper/Mappers/Phases/PBXSourcesBuildPhaseMapper.swift
  Sources/XcodeGraphMapper/Mappers/Project/ProjectAttribute.swift
  Sources/XcodeGraphMapper/Mappers/Settings/BuildSettings.swift
  Sources/XcodeGraphMapper/Mappers/Settings/XCConfigurationList+Helpers.swift
  Sources/XcodeGraphMapper/Mappers/Settings/XCConfigurationMapper.swift
  Sources/XcodeGraphMapper/Mappers/Targets/PBXTarget+BuildSettings.swift
  Sources/XcodeGraphMapper/Mappers/Targets/PBXTarget+GraphMapping.swift
  Sources/XcodeGraphMapper/Mappers/Targets/PBXTargetMapper.swift
  Tests/XcodeGraphMapperTests/MapperTests/Project/PBXProjectMapperTests.swift
  Tests/XcodeGraphMapperTests/MapperTests/Schemes/XCSchemeMapperTests.swift
  Tests/XcodeGraphMapperTests/MapperTests/Settings/BuildSettingsTests.swift
  Tests/XcodeGraphMapperTests/MapperTests/Settings/XCConfigurationMapperTests.swift
  Tests/XcodeGraphMapperTests/MapperTests/Target/PBXTargetMapperTests.swift
  Tests/XcodeGraphMapperTests/Mocks/MockDefaults.swift
  Tests/XcodeGraphMapperTests/TestData/PBXProject+TestData.swift
  Tests/XcodeGraphTests/Models/SettingsTests.swift
Labels: size:L, lgtm

#153 feat: Add `Target.validatedSources` to filter the sources that are invalid
  Sources/XcodeGraph/Models/Target.swift
Labels: enhancement, size:XS, lgtm
